version: '3'
services:
  app:
    image: 'docker-spring-boot-mysql:latest'  # Change the image name accordingly
    build:
      context: .
    container_name: cinema
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/db_cinema
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456


  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db_cinema
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10